#+title: Internet das Coisas Móveis (IoMT) e Coordenação de UAVs para aplicações do meio ambiente
#+subtitle: Seminário 11
#+options: toc:nil num:nil date:nil

A palestra abordou a importância da conectividade sem fio e intermitente na coordenação e orquestração de objetos móveis, produtos ou veículos para o funcionamento eficiente de nossas vidas, economia e meio ambiente.

A Internet das Coisas Móveis (IoMT) é caracterizada pelo movimento relativo entre coletores, hubs e dispositivos inteligentes (IoT) e pela conectividade intermitente proporcionada pela alcançabilidade do rádio WPAN. Além disso, o número de dispositivos IoT atendidos por cada coletor pode variar.

O projeto iniciou ao reconhecer que os smartphones são excelentes hubs para a coleta de dados desses dispositivos móveis. Os pesquisadores também colaboraram com a força aérea em um projeto chamado GrADyS, no qual coordenaram quadcópteros para transportar dados entre redes mesh.

O protocolo DADCA, desenvolvido para dispositivos IoT estacionários, adota uma heurística flexível e simples. Utiliza um padrão de movimento em zig-zag para cobrir uma área maior e transferir dados entre os drones e as estações de base.

Tais abordagens pussuem o potencial de melhorar a coordenação e a eficiência na coleta de dados, crucial para aplicações ambientais. Ao utilizar a Internet das Coisas Móveis e a coordenação de UAVs (veículos aéreos não tripulados), podemos obter informações valiosas, o que contribui para a preservação e o monitoramento do meio ambiente.
