#+title: Modelagem matemática para propagação de influência em redes sociais
#+subtitle: Seminário 9
#+options: toc:nil num:nil date:nil

A palestra discute a aplicação de modelos matemáticos na análise da propagação de informações e opiniões em redes sociais. Cada indivíduo é representado como um vértice em um grafo de conexão, e a velocidade de propagação das informações é determinada pela qualidade e conexão da rede. No caso das opiniões, a quantidade de vizinhos conectados que possuem a mesma opinião é relevante.

A palestra aborda a possibilidade de calcular o tempo necessário para disseminar uma opinião em toda a rede, assim como o número mínimo de influenciadores necessários para alcançar toda a rede a partir de um passo inicial. Também é mencionada a convexidade geodética, que se refere a um conjunto de vértices em que todos os caminhos mínimos passam apenas por nós do conjunto. A palestra destaca a importância desses modelos na compreensão de redes sociais reais, onde as pessoas podem ter requisitos diferentes de vizinhos para serem influenciadas e a rede pode sofrer alterações ao longo do tempo. Para muitas empresas, o conhecimento do número mínimo de influenciadores necessários para disseminar uma opinião de interesse é fundamental.
