#+title: Transformação Digital – Computação Escalar & Dados Digitais Intensivos
#+subtitle: Seminário 1
#+options: toc:nil num:nil date:nil

A computação escalável com uso intensivo de dados (DISC) é uma abordagem centrada em dados digitais que utiliza modelos de programação de alto nível e clusters de hardware para processamento. A estratégia de downsizing, que tentava diminuir o tamanho dos computadores, foi substituída pela abordagem de rightsizing, que permite a utilização de diferentes níveis de computação (edge, fog e cloud) para executar tarefas específicas de forma mais eficiente.

No contexto da DISC, os dados são coletados na borda, limpos e organizados para serem enviados para a “fog”, que agrega os dados e envia para processamento na nuvem. A análise desses dados permite a extração de informações valiosas para o conhecimento.

A DISC é aplicada em cenários de workflows de dados, paralelização massiva, logística de dados, processamento de stream, entre outros. É importante considerar a escalabilidade de entrada e saída de dados, a capacidade de armazenamento e o desempenho de acesso aos dados. Além disso, é necessário utilizar ferramentas específicas para cada uma dessas tarefas.

A simulação apropriada, de pós-processamento, in-situ e in-transit também é uma parte importante da abordagem DISC. Em resumo, a DISC é uma abordagem centrada em dados que requer uma organização e armazenamento eficientes dos dados, além de ferramentas específicas para processamento e simulação (pós-processamento, in-situ e in-transit).
