#+Title: Súmula Curricular
#+Subtitle: Programação Linear Inteira aplicada a problemas de Coloração em Grafos
#+options: toc:nil date:nil num:nil
#+latex_header: \usepackage[a4paper, total={6in, 8in}]{geometry}

* Formação
- Bacharelado em Ciência da Computação
- Instituto de Computação da Universidade Estadual de Campinas - UNICAMP
- Início: Março de 2018
- Conclusão: Dezembro de 2022

* Histórico Profissional
- Professor de programação para ensino médio :: (jan, 2022 - atual) Colégio e pré-vestibular Elite Campinas.
- Coordenador de unidade no UNICAMP de Portas Abertas :: (ago, 2022) Instituto de Computação da UNICAMP.
- Representante discente na Comissão de Graduação :: (abr, 2022 - dez, 2022) Instituto de Computação da UNICAMP.
- Representante discente na Congregação do Instituto de Computação :: (jul, 2021 - abr, 2022) Instituto de Computação da UNICAMP.
- Estagiário em desenvolvimento de software :: (mar, 2022 - abr, 2022) SF-Labs, Visio.
- Bolsista de Iniciação Científica :: (ago, 2019 - jul, 2020) Fundação de Amparo a Pesquisa do Estado de São Paulo
- Coordenador de cursinho popular :: (ago, 2018 - abr, 2019) Projeto Além da Escola
- Professor voluntário de programação em cursinho popular :: (mar, 2018 - abr, 2019) Projeto Além da Escola.
* Resultados
- da Silva FJ, Miyazawa FK, Romero IV, Schouery R. Tight Bounds for the Price of Anarchy and Stability in Sequential Transportation Games. arXiv preprint arXiv:2007.08726. 2020 Jul 17.
* Financiamentos à pesquisa
Recebi recursos correspondentes a bolsa de Iniciação Científica da Fundação de Amparo à Pesquisa do Estado de São Paulo no projeto *"Aplicações de Teoria dos Jogos Algorítmica a Problemas de Transporte"* (2019/14492-9) entre Agosto de 2019 e Julho de 2020, o qual recebeu conceito máximo.
* Indicadores quantitativos
Não se aplica
* Links
- ORCID :: orcid.org/0000-0002-5801-3774
* Outras informações
Ministrei dois workshops (git e python) para a graduação.
Nos últimos anos, me dediquei ao ensino de programação no ensino médio bem como em avançar na minha
** Premiações
- Primeiro lugar da turma de Ciência da Computação na UNICAMP
- Destaque IC e SBC
- Primeiro lugar do vestibular
