#+TItle: Prova de Inglês
#+Subtitle: Pós-graduação 2023
#+Author: Ieremies Vieira da Fonseca Romero (RA 217938)
#+options: toc:nil num:nil

* Question 1
a. A dificuldade de ingressantes no mercado da computação advindas de condições socioeconômicas e, principalmente, de terem frequentado universidades menos renomeadas. Dificuldades financeiras atreladas, reduzindo o tempo que pode ser dedicados a projetos paralelos, com a falta de valorização das empresas de tecnologia em relação a universidades menores, faz com que muitos não consigam se inserir no mercado.
b. O autor do texto cita a falta de reconhecimento de universidades mais acessíveis por parte do mercado; a condição socioeconômica dos alunos destas universidades não permitem que se dediquem a projetos paralelos, seus portfólios e hackatons, o que os coloca em desvantagem; grandes empresas do mercado tendem a dar preferências a candidatos com algum tipo de relacionamento com atuais empregados ou os próprios estagiários, mas já que muitos destes vêm das renomadas universidades, tais alunos que o texto trata sofrem ainda mais dificuldades.
c. O autor contribui positivamente ao assunto discutido trazendo-o a tona. Detalhes de recrutamento de empresas muitas vezes podem ficar escondidos ou isolados, sem que tenhamos uma perspectiva de mercado como um todo. Ele mostra como não são fatos isolados e muitas são as experiências frustrantes e injustas daqueles que tentam entrar no mercado de tecnologia, ajudando a tomarmos, como sociedade, consciência do problema.
* Question 2
Highly coveted internships at top tech companies, like Amazon and Google, can provide lifelong benefits, including the potential for full-time job openings and substantial pay. However, the typical recruitment process often gives an advantage to students from top IT schools and those with industry connections, and may have more time and opportunities to polish their portfolios and hone their testing skills. Most students spent hours applying for a huge number of internships, practicing for coding tests or working on personal projects to try to impress recruiters, all while having to work part-time, only to receive no offers. Students at lesser-known schools often lack industry, family, or elite university connections that lead to employee referrals. The intern selection process highlights long-standing inequalities in recruiting and hiring at tech companies, which have been exacerbated by the recent layoffs and cuts. Although some companies have some kind of inclusivity programs, those tend to just alleviate the problem rather than trying to systematically solve it.
